name: invoc
description: Invoc Flutter application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+17

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  path_provider: ^2.1.1
  http: ^1.1.0
  path: ^1.6.4
  image: ^4.1.3
  provider: ^6.1.1
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.0.6
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1
  sliding_up_panel: ^2.0.0+1
  fl_chart: ^0.36.2
  shimmer: ^3.0.0
#  progress_dialog: ^1.2.0
  progress_dialog_null_safe: ^1.0.7
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^2.0.9
  sembast: ^3.1.0+2
  checkdigit: ^0.3.0
  flutter_localization: ^0.1.14
  firebase_analytics: ^10.7.1
  firebase_crashlytics: ^3.4.5
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  expandable: ^5.0.1
  google_maps_flutter:
  motion_toast: ^2.6.8
  permission_handler:
  get: ^4.6.6
#  random_string: ^2.2.0-nullsafety
  google_sign_in: ^6.1.6
#  flutter_facebook_login: any
#  apple_sign_in: any
 # flutter_login_facebook: ^1.9.0
  sign_in_with_apple: ^5.0.0
  firebase_dynamic_links: ^5.4.5
  flutter_animated_dialog: ^2.0.1
  rxdart: ^0.27.1
  flutter_secure_storage: ^9.0.0
  package_info: ^2.0.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3



dependency_overrides:
  platform: ^3.1.0
  firebase_core_platform_interface: 5.0.0
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  dependency_validator: ^3.2.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fitness_app/
    - assets/address.json
    - assets/icons/
    - assets/fb-logo.png
    - assets/go-logo.png
    - assets/user.png

  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/sourcesanspro_bold.ttf

    - family: Gilroy
      fonts:
        - asset: assets/fonts/sourcesanspro_regular.ttf

    - family: GilroyHeavy
      fonts:
        - asset: assets/fonts/sourcesanspro_black.ttf

    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/sourcesanspro_regular.ttf

    - family: GillroySemiBold
      fonts:
        - asset: assets/fonts/sourcesanspro_semibold.ttf

    - family: GillroyExtraBold
      fonts:
        - asset: assets/fonts/sourcesanspro_black.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/apple_launcher_icon.jpg"
#  image_path: "assets/images/admin_launcer_icon.jpg"
